(TeX-add-style-hook
 "StarClassLibrary"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "twoside")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("hyperref" "dvips=true" "hyperindex=true" "colorlinks=true" "linkcolor=blue" "bookmarks=true")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art10"
    "graphicx"
    "color"
    "amsmath"
    "amssymb"
    "fancyhdr"
    "times"
    "verbatim"
    "makeidx"
    "subfigure"
    "hyperref")
   (TeX-add-symbols
    '("Entrylabel" 1)
    '("entrylabel" 1)
    '("args" 1)
    '("comp" 1)
    '("name" 1))
   (LaTeX-add-labels
    "Philosophy"
    "platformsAndCompilers"
    "Macros"
    "tab:templates"
    "SystemOfUnits"
    "sec:partTable"
    "sec:pex"
    "sec:predefpart"
    "tab:leptons"
    "tab:ions"
    "tab:bosons"
    "tab:mesons"
    "tab:baryons"
    "sec:umlPart"
    "fig:umlPart"
    "StAngle"
    "StFastCircleFitter"
    "StHbook"
    "StHelix"
    "StHelixD"
    "StLorentzVector"
    "StLorentzVectorD"
    "StLorentzVectorF"
    "StMath"
    "StMatrix"
    "StMatrixD"
    "StMatrixF"
    "StMemoryInfo"
    "StMemoryPool"
    "StPhysicalHelix"
    "StPhysicalHelixD"
    "ref:StPrompt"
    "StRandom"
    "StThreeVector"
    "fig:StThreeVector"
    "StRotation"
    "Random"
    "app:helix"
    "eq:xs"
    "eq:ys"
    "eq:zs"
    "fig:helix"
    "eq:dist"
    "eq:dsolve"
    "fig:dcahelices"
    "eq:rsolve"
    "fig:plane"
    "eq:ansatz"
    "eq:inter"
    "sec:Limitations"
    "sec:hparam")
   (LaTeX-add-environments
    "entry"
    "Entry")
   (LaTeX-add-index-entries
    "philosophy"
    "member functions"
    "Standard C++ Library"
    "CLHEP"
    "Standard Template Library"
    "compiler"
    "platform"
    "SCL"
    "HP-UX"
    "aCC (HP compiler)"
    "Linux"
    "Solaris"
    "Object Space"
    "Visual C++"
    "Irix"
    "AIX"
    "Accessing SCL"
    "afs"
    "CVS"
    "CVSROOT"
    "macros"
    "ANSI"
    "ST\\_NO\\_MEMBER\\_TEMPLATES"
    "ST\\_NO\\_EXCEPTIONS"
    "ST\\_NO\\_NUMERIC\\_LIMITS"
    "ST\\_NO\\_TEMPLATE\\_DEF\\_ARGS"
    "ST\\_NO\\_NAMESPACES"
    "ST\\_OLD\\_CLHEP\\_SYSTEM\\_OF\\_UNITS"
    "\\_\\_ROOT\\_\\_"
    "documentation"
    "class browser"
    "HTML"
    "limitations"
    "Sun"
    "bool"
    "StPrompt"
    "LD LIBRARY PATH"
    "cfront
        compiler"
    "StTemplates"
    "CINT"
    "ROOT"
    "support"
    "Physical Constants"
    "pi"
    "twopi"
    "halfpi"
    "pi2"
    "Avogadro"
    "c\\_light"
    "electron\\_charge"
    "electron\\_mass\\_c2"
    "HepDouble"
    "HepInt"
    "HepFloat"
    "HepBoolean"
    "StDouble"
    "StFloat"
    "StInt"
    "StLong"
    "StSizeType"
    "StNPOS"
    "sign()"
    "sqr()"
    "PR()"
    "System of units"
    "namespace"
    "GEANT3"
    "millimeter"
    "barn"
    "radian"
    "nanosecond"
    "microsecond"
    "hertz"
    "Hz"
    "MeV"
    "GeV"
    "mm"
    "rad"
    "mrad"
    "ns"
    "particles"
    "PDG encoding"
    "Geant3 Id"
    "StBMesonPlus"
    "StBMesonMinus"
    "StBMesonZero"
    "StBsMesonZero"
    "StDMesonPlus"
    "StDMesonMinus"
    "StDMesonZero"
    "StDsMesonPlus"
    "StDsMesonMinus"
    "StHe3"
    "StJPsi"
    "StAlpha"
    "StAntiBMesonZero"
    "StAntiBsMesonZero"
    "StAntiDMesonZero"
    "StAntiKaonZero"
    "StAntiLambda"
    "StAntiLambdacPlus"
    "StAntiNeutron"
    "StAntiNeutrinoE"
    "StAntiNeutrinoMu"
    "StAntiNeutrinoTau"
    "StAntiOmegaMinus"
    "StAntiOmegacZero"
    "StAntiProton"
    "StAntiSigmaPlus"
    "StAntiSigmaMinus"
    "StAntiSigmaZero"
    "StAntiSigmacPlus"
    "StAntiSigmacPlusPlus"
    "StAntiSigmacZero"
    "StAntiXiMinus"
    "StAntiXiZero"
    "StAntiXicPlus"
    "StAntiXicZero"
    "StDeuteron"
    "StPositron"
    "StElectron"
    "StEta"
    "StEtaPrime"
    "StGamma"
    "StKaonPlus"
    "StKaonMinus"
    "StKaonZero"
    "StKaonZeroLong"
    "StKaonZeroShort"
    "StLambda"
    "StLambdacPlus"
    "StMuonPlus"
    "StMuonMinus"
    "StNeutron"
    "StNeutrinoE"
    "StNeutrinoMu"
    "StNeutrinoTau"
    "StOmegaMinus"
    "StOmegacZero"
    "StOpticalPhoton"
    "StPionPlus"
    "StPionMinus"
    "StPionZero"
    "StProton"
    "StRhoPlus"
    "StRhoMinus"
    "StRhoZero"
    "StSigmaPlus"
    "StSigmaMinus"
    "StSigmaZero"
    "StSigmacPlus"
    "StSigmacPlusPlus"
    "StSigmacZero"
    "StTauPlus"
    "StTauMinus"
    "StTriton"
    "StXiMinus"
    "StXiZero"
    "StXicPlus"
    "StXicZero"
    "Geant4"
    "StParticleDefinition"
    "StParticleTable"
    "leptons"
    "ions"
    "bosons"
    "mesons"
    "baryons"
    "StAngle"
    "angles"
    "StFastCircleFitter"
    "circle fit"
    "StGetConfigValue|textbf"
    "StThreeVector"
    "STL"
    "StHbook|textbf"
    "cfortran.h"
    "StHelix|textbf"
    "Bock, R."
    "straight line"
    "StPhysicalHelix"
    "dca"
    "distance of closest approach"
    "StHelixD"
    "TObject"
    "StLorentzVector|textbf"
    "Heavy-Ion Physics"
    "boost"
    "Lorentz boost"
    "abs"
    "StLorentzVectorD"
    "StLorentzVectorF"
    "StMath"
    "math functions"
    "StMatrix"
    "vector"
    "StLorentzVector"
    "coding Guidelines"
    "StRotation"
    "StBoost"
    "StMatrixD"
    "StMatrixF"
    "StMemoryInfo"
    "memory info"
    "StMemoryPool"
    "memory allocation"
    "pool"
    "StPhysicalHelix|textbf"
    "StHelix"
    "StPhysicalHelixD"
    "StPrompt|textbf"
    "StRandom|textbf"
    "random numbers"
    "StTemplates|textbf"
    "cfront compiler"
    "StThreeVector|textbf"
    "StThreeVectorD|textbf"
    "StThreeVectorF|textbf"
    "StTimer|textbf"
    "timer"
    "CPU timer"
    "Random|textbf"
    "seed table"
    "GEANT4"
    "RandFlat"
    "RandGauss"
    "RandExponential"
    "RandPoisson"
    "RandBreitWigner"
    "helix parameters"
    "path length"
    "dip angle"
    "curvature"
    "phase"
    "dca between helices"))
 :latex)

